[project]
name = "prepare-testing-secrets"
version = "0.1.0"
description = "A script to prepare dummy secrets for testing/CI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["jinja2>=3.1.5", "rich>=13.9.4"]

[project.scripts]
prepare-testing-secrets = "prepare_testing_secrets:main"

[tool.setuptools.package-data]
prepare_testing_secrets = ["templates/*.j2"]
