hello: ENC[AES256_GCM,data:wwpVwghx9gosF6OM027suI4l2YymtstoqIhwtxVtP2oH6UIzCWltX7R2IiOCYA==,iv:fCa6aKCk3VkpHpmcEcIpW8n/98eJxt4VyJSkbhT6wnc=,tag:WlZ/b6O2Tgg85jU0QNncxA==,type:str]
example_key: ENC[AES256_GCM,data:6OK0cQVl9Jaxl/AuYQ==,iv:ez6vp8LcGpqAKxR9XQI+4AJakSYB7WJwja/L+AJAhWQ=,tag:o2NRyJse8t5PK/u9xOjq8w==,type:str]
#ENC[AES256_GCM,data:VEzWhiX8y+98wezil5ipPQ==,iv:vRmqsQOJdwUFzcWL9r/cITxBRWdn/ESuGSnX52D26Ek=,tag:Vl8Z20VYsmlofM9jNIwCaQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:lVt4AfP3wr/5uwjvQjw=,iv:Rh0eQjol4AiSTqMK5SWXH4dRBLRgJcHjugtzbd3mFms=,tag:Zz2UcFRY0B5hXpOOi/88Yw==,type:str]
    - ENC[AES256_GCM,data:87CHIRJrC7qeernhXTU=,iv:e2Tssue4dNGLczOvVdmplnnzmtl8APDoit7knwMvaIk=,tag:Q+/om0y3e7n62sIp3LSYGA==,type:str]
example_number: ENC[AES256_GCM,data:95DZ39cVnLLLig==,iv:6p3Z9z+m8Zmd/6byew9BhVWc2BO3JgcZDGOBLNQe7kA=,tag:uFj1UCRUnLSxyUFHwfy9UQ==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:tCT1nQ==,iv:WTQMXFPXUYA2/aAPzqHQPKZiB3F5fD9NKH/+VP0u85I=,tag:aCmctOokdmpcLyhzVq7XqQ==,type:bool]
    - ENC[AES256_GCM,data:xi2JmdM=,iv:KSQ8mdiLZOhzbWDfbHZWKYEXcBh8F0NQKpwnFRvBhv8=,tag:R63rU6hNLkBiI+l/TOE6Zw==,type:bool]
sops:
    shamir_threshold: 2
    key_groups:
        - pgp:
            - created_at: "2025-10-28T15:54:51Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hF4D/MhE8/R4AWcSAQdALmBgJfr3CJYgBaGOa9ZAvA0q5OPRouDuF+xqjWfHq1sw
                YPYWkNhXR92dhtPb83mJdyREzMHuUC5as1KJGxee7FEzkE7XpIz9tXIxFvVZb0D4
                0l0BC/mNaUHFsK1sU756gk4O5galyO7qMHIwaHuKSzed+AdzwW1KzYmr7DXt2aVS
                eCdWecYlA75acNIKVY59pUM3uMyJcKH68lM6rtdlE7ZT62bjkIm14j2qyfmp7ec=
                =Js1n
                -----END PGP MESSAGE-----
              fp: C5DC80511469AD81C84E3564D55A35AFB2900A11
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1lg9zurerznuekamjlkvvvshh68ahawpfzgzzvxn5lq4lrrpqjskqzjf6v2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRTBlMUcxZllZTzc4TjBJ
                L1hnMkhlWVJUS0RHRDJQd1FsRG9EaUR4NGxrCmN5OURzVDMrVkJSWTVTdmo3ZXZI
                dmkrTXdaQkd5Zi80cTFQQi81MlozZzgKLS0tIC9tdzhVZFpJMGI1YWVqaEJ5RVM4
                ZGh2a3RheGFoZmRyM0dyU21HWGl4T2cK21fsjcyuGBKsGU1cqkjolOokJZfM75P3
                JG7IEf4mNvb7+cLLETMMxSkn181io6rMlIB+fGBggJGQaX3R5Y1zwFI=
                -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T15:54:37Z"
    mac: ENC[AES256_GCM,data:aYHFd6cEsTVIVPX4Hdqm7ncSDqDlSYzafwqb/8Qlt/90DaDsxUkgqeR6MEhGNc9YdZhnU58ckHlyxxgFkNzz9FPAnYtxn4fdv8qlHME4a+yHD729KqRprbGSVES+yUHUKsQc1FGzJpFkwDwKkBeUpeC05rWkyzEPborto3/hLLs=,iv:ZRHOqmucRLp9cZUTVtONhbDJV6HC0PvdqjBHdXPkvko=,tag:wc0jgtFNX7Cnv1gOaGnYlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
