services:
    tailscale:
        auth_key: ENC[AES256_GCM,data:lgbTUqo=,iv:zpo27fh0NgouWMrGDDYrdYPJ8WvfS/f53tsDu4IzyTk=,tag:sVgML4zqWEzItRfeyOAbKA==,type:str]
sops:
    age:
        - recipient: age1vev3hxns4t0lzwndl2nt6wd2xucr0kzqhvprxskysh0gj7j8retsckk04a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYU1wcDcrM1lqeG9NaUQ4
            SHB6NEJUOERuV0lwQ01CYWxwU2NrTk53WlZ3CjQ5UkVtTTdGUllUWWJHR1BvYlFG
            UXFndVBsbkhtWWhQU2ZTaDQyZ0xSeHMKLS0tIEtJZm1yRVozbDRHQk9LU1Q0MlpX
            Q3l1N21tYyt3TFVONm9VYVFWZEdFbm8KyMeGHASWknwwXFDw1FDjtBDcjrWIRD+H
            1FN3W3qNf6cFRgYo15OoOlYGoGsHsf61PIlW7ZThUnwXMQ1XNfWN9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1td4wjw2z3f5qtvp38vxqretjap4svn23m4e22tmktw6jpms6xfusxejtj6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY1FENGpUUVN2Q2NFcSth
            QVUrOWdEZjVxNlIyUysxUXZHdENDeG1qZ2wwCklDVkJpRUJqd0tZbW9aZjRLWndV
            aENKZDY1VzBqZUdzUkppcG5GYlJ4cGMKLS0tIElneFlXdlRPNmI1S1ZtTG9KWEM5
            R2RCK3hZYzhKL0Q1ZWxFSWRZdG9sMncKVERRh5iUf8O3N7smOkcyF8AKq0p/TAs5
            jgDewo+ljPC3jFWu4WEmBriE+JVdiaWkbFu15ySCe5CXjNBdqLPPXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T00:49:50Z"
    mac: ENC[AES256_GCM,data:88ka3n1yWYvyYtW3DFlZP8e1VKa7wBN1XfaZLut0GELPNB1LzNZdDZWX3lj7v8L9RywhwfYeJvk8gCo2FQ3uUOuHRSPRMoJxGITYHyOu4LmFX9M370RTi9GgXDAbDUKTCsvx89x/rEZk7k3eUqJHF4nMXDV0vmJBK/QgqKxOUHk=,iv:9WScLrO9+jGsRrD0KI2uLFt9guJIpjrKJDZGmoUP78k=,tag:M7GJZV2/3WXssLip98rDjw==,type:str]
    pgp:
        - created_at: "2025-10-29T00:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/MhE8/R4AWcSAQdAxq4UNuOnu2j55ricvsf/TFzij0mfs4fmLDpsEdhqFRIw
            r5FEQZ5BGYUQNdzelbpK95j+ZU8ymAVB+QmlNNAZyrUYkU70RcycVNjXfB7Q4OgZ
            0lwBstLa/Y5H8EGfaEov8Or355pfFq+1IOPn/8qUCXRGIKpY5+D3Jl/eXvRRR98u
            Isf9MavY8ZSiB1RMjalFL/uKjAI8lnT0wh+jE3zRIdireatEcNmZdUoI9IpKOg==
            =XP5J
            -----END PGP MESSAGE-----
          fp: C5DC80511469AD81C84E3564D55A35AFB2900A11
    unencrypted_suffix: _unencrypted
    version: 3.11.0
