services:
    tailscale:
        client_id: ENC[AES256_GCM,data:m4qQyb/ElQwGYu74V/ADS+k=,iv:c4dCH6q4i6YAOdUg5HmlIZswGfkdcSWejkXUtiLjtUk=,tag:cusXunhDjBLnr7eddeOaPA==,type:str]
        client_secret: ENC[AES256_GCM,data:Y0epFNkAT/8ZIt/1/U8CxjVHzPZeuNSnnGdMi9XqKsRoACcPfFzQVm8+tnZqrjT3/XmhxpoByU34zm6Nz2XcVQ==,iv:UzjzKohAFc+NIedOPXDdRhhnxV5cekgKiy9DNRW8QI0=,tag:BG8hgXkh79ASgFaTDnVYPQ==,type:str]
sops:
    lastmodified: "2025-10-31T06:40:41Z"
    mac: ENC[AES256_GCM,data:Q3IVHNaJzTHVD2g+qDpFGUX6gaNyupHGOtkv2MGj8kl8Cf+do8ahwO30hwqKUAVyWs+AQ8iBIaZZ65idw75HN7uvD0dsWwARuTiOqzor55XMPLmhdzNFaxSBg8IUEiLDulKVao8n+nEpuph8mX++co57dK/9frAjyE6voZg/K0A=,iv:yVLIh+oMAnVrm8dFNNTmxuMhXxhrZngROC7gOzEo2cc=,tag:ZcG2EQRG84igC+B5sbVCJg==,type:str]
    pgp:
        - created_at: "2025-10-31T06:39:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/MhE8/R4AWcSAQdAAw+6YcTlCFVhb4aqeWO1phlOjlzwjzZBoOWZp4KdxzAw
            di2slscCQY/qMVgMzJHyS9RXCPbymbiiDsoMkY0UwqoN7S6vE/EQull0ByLdJcsH
            0lwBs2oCtPtqaGMSvAmMpW3Uwf3OTVOLyq5JjuQKzZPSqVbhDN+AvDNl0MdgMhSA
            EvaZA2z8Qbel/wJtGxGTyFpJH2ZWPUsEIfP9Ix4OCW6MqaFgz3P6eMS0sNFBHw==
            =xBqT
            -----END PGP MESSAGE-----
          fp: C5DC80511469AD81C84E3564D55A35AFB2900A11
    unencrypted_suffix: _unencrypted
    version: 3.11.0
