services:
    tailscale:
        client_id: ENC[AES256_GCM,data:m4qQyb/ElQwGYu74V/ADS+k=,iv:c4dCH6q4i6YAOdUg5HmlIZswGfkdcSWejkXUtiLjtUk=,tag:cusXunhDjBLnr7eddeOaPA==,type:str]
        client_secret: ENC[AES256_GCM,data:Y0epFNkAT/8ZIt/1/U8CxjVHzPZeuNSnnGdMi9XqKsRoACcPfFzQVm8+tnZqrjT3/XmhxpoByU34zm6Nz2XcVQ==,iv:UzjzKohAFc+NIedOPXDdRhhnxV5cekgKiy9DNRW8QI0=,tag:BG8hgXkh79ASgFaTDnVYPQ==,type:str]
home:
    age:
        public_key: ENC[AES256_GCM,data:DChNo1syve4kSYiaNaetwRHIvt68FjzBq3c9NJpyvp2WnjWdh7B7BYrsCobx8CjtXPk5jb0ZZqJw3XAuEYQ=,iv:zActwAEPrKe+Bgx/BlbvSn9VSh4nrgktznORX8n2xlE=,tag:2CLcHhxBSVbK45pYZWmhRQ==,type:str]
        private_key: ENC[AES256_GCM,data:PQUwpVGiivnjsNuNkX4gZgwTZ2FWQpwO/9MyzJCKgY7XWCUx1so3Ui1KA7fMpYmaMd4Caj4+WxpQ0bJZkwc/HvgJo6jEVi857lE=,iv:SccOiWhmT0DuTrfDATGJXqyydvTlmfa0BTMAGY6dKHQ=,tag:NcbUSeTYB9a1veAslO8qZA==,type:str]
sops:
    age:
        - recipient: age1qhfem3f8dad2d0zlutclfs4az3k9e5ql7jflceaxu8fug4xh2s5s03rmxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VlFKNGVRNzRteDN4NFZa
            NXpUL2dtc1VKTmI4NDRaVHFCbVFIT1luYWpnCjVXWE9XOVR2UThwQnBiTklPVmgr
            c3NzU0w0dzNITWl0ZTA5RU9MbjZtdTgKLS0tIHVmbmFSNkd5ZGliNjRFcEZuRDBj
            TWw4WUFoemVZVVhwUk5zTFE5UFFVQ28KIL7tYQK5fqhfdOxC6eQltxmKWPr1yWOu
            rP7IeaSiAj7znCxwSVgSixDaVLZ2F2roeyumXsnCFXzzyc0/O06spw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c6wr89lzrrlnqkq5tyqktetl8lntg6m7jm09mmldczah57t9euks9z8z4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSm1HOW9GKzZvSDZnRWph
            R1ZCSm8zbHNhSE9WMjlIZ3hzNkVZRWtMZ1FJCmJVZUJiVVQ5a3dodkFiM3hsZTVP
            VlJWY3ltdFVBRGNRbkJtblMrVUkvc1kKLS0tIEtLRXRWKzc0VWZqekNCK294NEpv
            d2ZjOWlpYXc2TFQ3SEsvcmNoY1VkbTAK+9TmQXmAmurcXXRjovgY67qRk6ehQE+C
            rDxbbe3q/tXDbhL6T1eXkUENVuGJW3dy0R4c0GEPfIjoAPLtJHpUWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T08:09:07Z"
    mac: ENC[AES256_GCM,data:g3k9pSknDjjdjj5A00R31eAsKK3t0wTh4YEc3l9F2cd2nukJLPfrpc4cQFTteQhe7Ly/t7itsdc358LdxFnPKNoiOqDwhh5pAEawWUP2ninUistIhDaW4LfwTlKY5n5UBUrmc8h4nLecMa4jXirXBWkBES8T5uWnZAsqIyaF+9A=,iv:aQtBuXU7orJ/ImghTyl2YvAvyBfGqOXnmfA+Gm/X2Dg=,tag:c7L8Yw1DH3qpJQtidh48xA==,type:str]
    pgp:
        - created_at: "2025-10-31T09:04:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/MhE8/R4AWcSAQdAWGQZ6MUyntNsdZpPT3epEfCNaUh/68Cc5tn2AsOWiGow
            s0iylnExcfn4uY1BhBQlpJ8T/RkgWnJSz03NOmWgA7QXcSXyuXUbpa55bXB6pIuQ
            0lwBT+dqSoFZBDaS5qhfFJhvvyWu1I0QB2qes3RzYAFba751k2M2wToMqN6HHH1R
            dn9Ed+4QzbajpOJK+GdXkUM1NUG/Tv6a9HkE+6UsbNb+1JvW7j31DEHeZjM2/A==
            =8N7x
            -----END PGP MESSAGE-----
          fp: C5DC80511469AD81C84E3564D55A35AFB2900A11
    unencrypted_suffix: _unencrypted
    version: 3.11.0
