test: ENC[AES256_GCM,data:wVfpnd8=,iv:YLYgFE61fSHdCdo1PDIo8MV8B7xsy2p+WvUxIIfM8bQ=,tag:nquYt1nvhQomDvuwOE42pw==,type:str]
sops:
    lastmodified: "2025-10-28T13:36:18Z"
    mac: ENC[AES256_GCM,data:f1ovwkFnQt8bt9hpOtMHhimX845taM9FErwxbwV3GNza4eaCxkSVaZXhLtoE5qIZ+Gz1s+BvrbvmLYXuvcFFOzfWnpMJ0MRBv60BrZLVOG/9UVtXVrnrVpTst3LPqaxPhFHTa6fh4WANVFrBp3HmRbbdM+dDtpJRjvovOhkypnM=,iv:D4nKapYHN0/9lArxBBiCvlWO+5Afhwcys7mGYTiixXw=,tag:ah1N/lpSCWGbsCGWqTLDDw==,type:str]
    pgp:
        - created_at: "2025-10-28T13:36:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/MhE8/R4AWcSAQdAe1M875EQUWugXIBn/gr4ZQfyo3xMfQ3ltU5lG27hpyAw
            +UYCW4dLcpD54Ri8zQOcesTc53uJ07A324V6IS4ZYSerI+kVk3wdGzBNGO5D/fSs
            0l4B9XYzQL5Rro2Dk5Ufqi2s5kDTk2grYwPuCCG+F24DElGrBf03y+p7gzf44TdU
            NiESsF4WAUsANL9faEI/lXf8G6fIQp7VAsvd5+ZwYVf6mRKq+o5GR3uL7JnlSl54
            =aqOH
            -----END PGP MESSAGE-----
          fp: C5DC80511469AD81C84E3564D55A35AFB2900A11
    unencrypted_suffix: _unencrypted
    version: 3.11.0
