---
keys:
  - &gpg_fkoehler C5DC80511469AD81C84E3564D55A35AFB2900A11
  - &ssh_fkt14 age15qceufnzv3dv2ktnulg7dd2cjwp4cncjkhqznrxadnv44llcaulqajpve7
  - &ssh_homeserver age1gltr5ymzr6mzsv5f2sks9sn9x0all9nkzge6ffvuaz9yvxhflflsxsdkx9
  - &ssh_vps age1p9lu539mlanywxcpymnaq5uuuxmuthkg2p4zcgfynr6ynwfmtatq9j4vy6
creation_rules:
  - path_regex: secrets/(home|common)\.yaml$
    key_groups:
      - pgp:
          - *gpg_fkoehler
        age:
          - *ssh_fkt14
          - *ssh_homeserver
          - *ssh_vps
  - path_regex: secrets/vps\.yaml$
    key_groups:
      - pgp:
          - *gpg_fkoehler
        age:
          - *ssh_vps
  - path_regex: secrets/homeserver\.yaml$
    key_groups:
      - pgp:
          - *gpg_fkoehler
        age:
          - *ssh_homeserver
