---
keys:
  - &gpg_fkoehler C5DC80511469AD81C84E3564D55A35AFB2900A11
  - &ssh_fkt14 age15qceufnzv3dv2ktnulg7dd2cjwp4cncjkhqznrxadnv44llcaulqajpve7
creation_rules:
  - path_regex: secrets/(home|common)\.yaml$
    key_groups:
      - pgp:
          - *gpg_fkoehler
        age:
          - *ssh_fkt14
