creation_rules:
- path_regex: \.secrets.yaml$
  key_groups:
  - pgp:
    - C5DC80511469AD81C84E3564D55A35AFB2900A11       # fkoehler
  - age:
    - age1lg9zurerznuekamjlkvvvshh68ahawpfzgzzvxn5lq4lrrpqjskqzjf6v2  # host: 192.168.122.134, config: homeserver-dev
