[project]
name = "run-cmd-with-lock"
version = "0.1.0"
description = "Acquire a lock file for running a command"
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
authors = [{ name = "Fabian Koehler", email = "fabian.koehler@proton.me" }]
maintainers = [{ name = "Fabian Koehler", email = "fabian.koehler@proton.me" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "Intended Audience :: System Administrators",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Unix Shell",
  "Topic :: Home Automation",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
  "Topic :: System",
  "Topic :: Utilities",
]
dependencies = ["typer>=0.15.2"]
